dist: xenial
language: php

# Host (https://docs.travis-ci.com/user/hosts)
addons:
  chrome: stable
  hosts:
    - romainnorberg.local
    - resume.romainnorberg.local
    - blog.romainnorberg.local

matrix:
  fast_finish: true
  include:
    - php: 7.3
    # 'php: nightly' is PHP 8.0
    - php: 7.4snapshot
  allow_failures:
    - php: 7.4snapshot

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  - composer install

script:
  - phpunit

