#on: [push]
#name: Main
#jobs:
#  php-cs-fixer:
#    name: PHP-CS-Fixer
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: src
#        uses: docker://oskarstark/php-cs-fixer-ga
#        with:
#          args: ./src --config=.php_cs.dist --diff --dry-run
